[package]
name = "snarkvm-circuit-environment"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Circuit environment for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[[bench]]
name = "linear_combination"
path = "benches/linear_combination.rs"
harness = false

[dependencies.console]
package = "snarkvm-console-network"
path = "../../console/network"
version = "0.7.5"

[dependencies.snarkvm-circuit-environment-witness]
path = "./witness"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-curves]
path = "../../curves"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-fields]
path = "../../fields"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-r1cs]
path = "../../r1cs"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.7.5"
default-features = false

[dependencies.indexmap]
version = "1.8.2"

[dependencies.itertools]
version = "0.10.1"

[dependencies.nom]
version = "7.1"

[dependencies.num-traits]
version = "0.2"

[dependencies.once_cell]
version = "1.12.0"

[dev-dependencies.snarkvm-algorithms]
path = "../../algorithms"
version = "0.7.5"
default-features = false
features = ["polycommit_full", "snark"]

[dev-dependencies.snarkvm-circuit]
path = "../../circuit"
version = "0.7.5"

[dev-dependencies.snarkvm-console-types]
path = "../../console/types"
version = "0.7.5"

[dev-dependencies.criterion]
version = "0.3"

[features]
default = ["snarkvm-curves/default", "snarkvm-r1cs/default"]
