[package]
name = "snarkvm-circuit-types-boolean"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Boolean circuit for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[[bench]]
name = "and"
path = "benches/and.rs"
harness = false

[dependencies.console]
package = "snarkvm-console-types-boolean"
path = "../../../console/types/boolean"
version = "0.7.5"
optional = true

[dependencies.snarkvm-circuit-environment]
path = "../../environment"
version = "0.7.5"

[dev-dependencies.criterion]
version = "0.3"

[features]
default = ["enable_console"]
# Use #[cfg(console)] instead.
enable_console = ["console"]
