apiVersion: apps/v1
kind: Deployment
metadata:
  name: verify
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: marlinverify
  template:
    metadata:
      labels:
        app.kubernetes.io/name: marlinverify
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: marlinverify
        tty: true
        image: ubuntu:latest
        ports:
        resources:
          limits:
            cpu: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.coreweave.cloud/cpu
                operator: In
                values:
                 - intel-xeon-v4
              - key: failure-domain.beta.kubernetes.io/region
                operator: In
                values:
                  - LAS1
      restartPolicy: Always
