[package]
name = "snarkvm-console-program"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Program operations for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-console-account]
path = "../account"
version = "0.7.5"

[dependencies.snarkvm-console-network]
path = "../network"
version = "0.7.5"

[dependencies.snarkvm-console-types]
path = "../types"
version = "0.7.5"

[dependencies.enum_index]
version = "0.2"

[dependencies.enum_index_derive]
version = "0.2"

[dependencies.indexmap]
version = "1.8"

[dependencies.num-derive]
version = "0.3"

[dependencies.num-traits]
version = "0.2"

[dependencies.once_cell]
version = "1.12.0"

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.serde_json]
version = "1.0"
