apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtx4000
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poswselector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poswselector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: posw
        command: ["/usr/bin/bash"]
        args: ["-i"]
        tty: true
        image: nvidia/cuda:11.8.0-devel-ubuntu22.04
        ports:
          - name: ssh
            containerPort: 22
        resources:
          limits:
            cpu: 16
            memory: 5Gi
            nvidia.com/gpu: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.coreweave.cloud/cpu
                operator: In
                values:
                 - intel-xeon-scalable
              - key: failure-domain.beta.kubernetes.io/region
                operator: In
                values:
                  - LAS1
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - Quadro_RTX_4000
      restartPolicy: Always
